# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotoEditor' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhotoEditor
  pod 'SwiftLint'
  pod 'FlexColorPicker', '1.4.4'

end
